language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install coverage
    - pip install numpy

before_script:
    - make versions

script:
    - date
    - ls -al
    - make config
    - make test
