language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - uname -a
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install python-numpy

before_script:
    - make versions

script:
    - make test
