language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install python-numpy

before_script:
    - make versions

script:
    - cd examples
    - make test
    - cd -
    - cd exercises
    - make test
    - cd -
    - cd projects/collatz
    - make collatz-tests
    - make Collatz.html
    - make Collatz.log
    - make test
    - make check
    - cd -
    - cd quizzes
    - make test
    - cd -
